project_id = "pduhecmerwvmgbdtathh"

[functions.create-checkout]
verify_jwt = true

[functions.wincova-github-commit]
verify_jwt = true

[functions.grant-welcome-bonus]
verify_jwt = false

[functions.process-referral]
verify_jwt = false

[functions.verify-payment]
verify_jwt = true

[functions.ai-suggest-tasks]
verify_jwt = true

[functions.ai-detect-risks]
verify_jwt = true

[functions.ai-generate-roadmap-tasks]
verify_jwt = true

[functions.ai-analyze-task-completion]
verify_jwt = true

[functions.calculate-roadmap-metrics]
verify_jwt = false

[functions.send-webhook]
verify_jwt = false

[functions.calculate-analytics]
verify_jwt = true

[functions.wincova-diagnose]
verify_jwt = false

[functions.wincova-compliance-check]
verify_jwt = false

[functions.wincova-generate-visuals]
verify_jwt = false

[functions.market-sources-health-check]
verify_jwt = false

[functions.wincova-execute-task]
verify_jwt = true

[functions.transform-to-customer-benefits]
verify_jwt = false

[functions.generate-roadmap-insights]
verify_jwt = false

[functions.generate-changelog-image]
verify_jwt = false

[functions.translate-feature]
verify_jwt = false

[functions.auto-translate-content]
verify_jwt = false

[functions.batch-translate-products]
verify_jwt = true

[functions.translate-api]
verify_jwt = false

[functions.woocommerce-create-order]
verify_jwt = true

[functions.woocommerce-webhook-handler]
verify_jwt = false

[functions.translate-secure]
verify_jwt = true

[functions.cart-storage]
verify_jwt = false

[functions.get-csrf-token]
verify_jwt = false

[functions.referral-storage]
verify_jwt = false
