project_id = "pduhecmerwvmgbdtathh"

[functions.create-checkout]
verify_jwt = true

[functions.grant-welcome-bonus]
verify_jwt = false

[functions.process-referral]
verify_jwt = false

[functions.verify-payment]
verify_jwt = true

[functions.ai-suggest-tasks]
verify_jwt = true

[functions.ai-detect-risks]
verify_jwt = true

[functions.send-webhook]
verify_jwt = false

[functions.calculate-analytics]
verify_jwt = true

[functions.wincova-diagnose]
verify_jwt = true

[functions.wincova-compliance-check]
verify_jwt = true
