project_id = "pduhecmerwvmgbdtathh"

[functions.create-checkout]
verify_jwt = true

[functions.grant-welcome-bonus]
verify_jwt = false

[functions.process-referral]
verify_jwt = false

[functions.verify-payment]
verify_jwt = true
